### ISSUE TITLE
영어 번역 지워주세요

### ISSUE THREAD

**Issue by ARD-a11y** [abiriadev/CodingLab-rules#1]
어차피 한국인밖에 없는데 불필요한 부분이라고 생각합니다.

그리고 보니깐 완벽한 번역도 아니고요.

영어 부분 지워주시면 감사하겠습니다.

**Comment by abiriadev** [comment]
> 어차피 한국인밖에 없는데 불필요한 부분이라고 생각합니다.
> 
> 그리고 보니깐 완벽한 번역도 아니고요.
> 
> 영어 부분 지워주시면 감사하겠습니다.

일단 깃허브에서는 외국인들도 이 저장소를 볼 수 있기 때문에 영어를 표시해 놓는 것이 예의라고 생각합니다.

**Comment by abiriadev** [comment]
이제 이슈를 닫겠습니다.
