### ISSUE TITLE
아악

### ISSUE THREAD

**Issue by aNchor-only** [abiriadev/CodingLab-rules#17]
![image](https://user-images.githubusercontent.com/73648912/98774268-02dc0000-242e-11eb-91db-1d20ab09b70e.png)
무슨

**Comment by abiriadev** [comment]
으앗

**Comment by abiriadev** [comment]
음....

@aNchor-only 님의 포크 쪽 브랜치가 잘못 선택된거 같은데요.

anchor브랜치 말고 변경사항이 들어있는 다른 브랜치로 시도해 보세요.

**Comment by aNchor-only** [comment]
anchor 브랜치에 변경사항이 들어있는데요

**Comment by abiriadev** [comment]
음...?

구글링 하셔서 알아보세요.

단순 병합충둘이면 제쪽에서 문제가 납니다.

@aNchor-only
